const menus = [
    {
      name: "Ensalada César",
      description: "Una fresca ensalada con aderezo César.",
      image: "ensalada-cesar.jpg",
      price: 9.99,
      active: true,
      category: "entrada",
    },
    {
      name: "Filete de Ternera",
      description: "Un jugoso filete de ternera a la parrilla.",
      image: "filete-ternera.jpg",
      price: 18.99,
      active: true,
      category: "parrilla",
    },
    {
      name: "Tiramisú",
      description: "Un delicioso postre italiano de café y mascarpone.",
      image: "tiramisu.jpg",
      price: 6.99,
      active: true,
      category: "dulces",
    },
    {
      name: "Café Latte",
      description: "Un café latte recién preparado.",
      image: "cafe-latte.jpg",
      price: 3.49,
      active: true,
      category: "cafeteria",
    },
    {
      name: "Vino Tinto Cabernet Sauvignon",
      description: "Un vino tinto de cuerpo completo.",
      image: "vino-cabernet.jpg",
      price: 14.99,
      active: true,
      category: "vinos",
    },
    {
      name: "Sopa de Tomate",
      description: "Una sopa de tomate casera con hierbas frescas.",
      image: "sopa-tomate.jpg",
      price: 7.99,
      active: true,
      category: "entrada",
    },
    {
      name: "Costillas BBQ",
      description: "Costillas de cerdo bañadas en salsa barbacoa.",
      image: "costillas-bbq.jpg",
      price: 16.99,
      active: true,
      category: "parrilla",
    },
    {
      name: "Pastel de Chocolate",
      description: "Un pastel de chocolate rico y suave.",
      image: "pastel-chocolate.jpg",
      price: 5.99,
      active: true,
      category: "dulces",
    },
    {
      name: "Café Espresso",
      description: "Un café espresso fuerte y aromático.",
      image: "cafe-espresso.jpg",
      price: 2.99,
      active: true,
      category: "cafeteria",
    },
    {
      name: "Chardonnay",
      description: "Un vino blanco Chardonnay bien equilibrado.",
      image: "vino-chardonnay.jpg",
      price: 12.99,
      active: true,
      category: "vinos",
    },
    {
      name: "Bruschetta",
      description: "Pan tostado con tomate fresco, ajo y albahaca.",
      image: "bruschetta.jpg",
      price: 8.99,
      active: true,
      category: "entrada",
    },
    {
      name: "Bistec a la Parrilla",
      description: "Un jugoso bistec a la parrilla con salsa de champiñones.",
      image: "bistec-parrilla.jpg",
      price: 19.99,
      active: true,
      category: "parrilla",
    },
    {
      name: "Mousse de Frambuesa",
      description: "Un suave mousse de frambuesa con decoración de frutas.",
      image: "mousse-frambuesa.jpg",
      price: 7.49,
      active: true,
      category: "dulces",
    },
    {
      name: "Café Mocha",
      description: "Un café mocha con crema batida y chocolate rallado.",
      image: "cafe-mocha.jpg",
      price: 4.49,
      active: true,
      category: "cafeteria",
    },
    {
      name: "Merlot",
      description: "Un vino tinto Merlot suave y afrutado.",
      image: "vino-merlot.jpg",
      price: 13.99,
      active: true,
      category: "vinos",
    },
    {
      name: "Rollitos de Primavera",
      description: "Rollitos de primavera rellenos de verduras y carne de pollo.",
      image: "rollitos-primavera.jpg",
      price: 6.99,
      active: true,
      category: "entrada",
    },
    {
      name: "Brochetas de Pollo",
      description: "Brochetas de pollo a la parrilla con verduras frescas.",
      image: "brochetas-pollo.jpg",
      price: 15.99,
      active: true,
      category: "parrilla",
    },
    {
      name: "Tarta de Manzana",
      description: "Una tarta de manzana casera con canela y helado de vainilla.",
      image: "tarta-manzana.jpg",
      price: 5.99,
      active: true,
      category: "dulces",
    },
    {
      name: "Café Americano",
      description: "Un café americano suave y refrescante.",
      image: "cafe-americano.jpg",
      price: 3.99,
      active: true,
      category: "cafeteria",
    },
    {
      name: "Malbec",
      description: "Un vino tinto Malbec robusto y lleno de sabor.",
      image: "vino-malbec.jpg",
      price: 14.49,
      active: true,
      category: "vinos",
    },
  ];

  export default menus;